-- Create database
CREATE DATABASE IF NOT EXISTS STRIPE_OLAP;

-- Switch to it
USE DATABASE STRIPE_OLAP;

-- Create schema (inside STRIPE_OLAP)
CREATE SCHEMA IF NOT EXISTS RAW;

-- Switch to that schema
USE SCHEMA RAW;

-- Create compute warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_STRIPE_OLAP
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE OR REPLACE FILE FORMAT CSV_WITH_BOOL
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  BOOLEAN_TRUE = 'True'
  BOOLEAN_FALSE = 'False';


-- Optionally: grant access to analyst role (replace with actual role name)
-- GRANT USAGE ON DATABASE STRIPE_OLAP TO ROLE ANALYST;
-- GRANT USAGE ON SCHEMA STRIPE_OLAP.RAW TO ROLE ANALYST;
-- GRANT SELECT ON ALL TABLES IN SCHEMA STRIPE_OLAP.RAW TO ROLE ANALYST;
-- GRANT SELECT ON FUTURE TABLES IN SCHEMA STRIPE_OLAP.RAW TO ROLE ANALYST;
